import { canonicalSessionLanguage } from "./language.ts";

export const SERVICE_LANGUAGES = Object.freeze(["en", "uk", "es", "fr", "de", "pl", "ru"] as const);
type ServiceLanguage = typeof SERVICE_LANGUAGES[number];
export function supportedServiceLanguage(language: string | null | undefined): ServiceLanguage | undefined {
  const primary = canonicalSessionLanguage(language)?.split("-")[0];
  return SERVICE_LANGUAGES.find(item => item === primary);
}
export const LANGUAGE_QUESTION = "🌐 Which language? / Якою мовою? / ¿En qué idioma? / Quelle langue ? / Welche Sprache? / W jakim języku? / На каком языке? — English · Українська · Español · Français · Deutsch · Polski · Русский";

type Translations = Readonly<Record<ServiceLanguage, string>>;
const entry = (uk: string, en: string, es: string, fr: string, de: string, pl: string, ru: string): Translations => Object.freeze({ uk, en, es, fr, de, pl, ru });
export const SERVICE_MESSAGES = Object.freeze([
  entry("Перед початком потрібна ваша одноразова згода на обробку звичайних бізнес-даних обраними ШІ-провайдерами. Не надсилайте паролі, ключі доступу, повні банківські реквізити чи державні ідентифікатори. Напишіть «Погоджуюсь на обробку» або «Не погоджуюсь». Це не дозвіл на зовнішні дії чи чутливі документи.",
    "Before starting, I need your one-time consent for the selected AI providers to process ordinary business information. Do not send passwords, access keys, complete bank details or government identifiers. Reply “I consent to processing” or “I do not consent”. This does not authorise external actions, intrusive personal exploration or sensitive documents.",
    "Antes de empezar, necesito tu consentimiento para que los proveedores de IA seleccionados procesen información empresarial ordinaria. No envíes contraseñas, claves, datos bancarios completos ni identificadores oficiales. Responde «Acepto el tratamiento» o «No acepto». Esto no autoriza acciones externas, exploración personal intrusiva ni documentos sensibles.",
    "Avant de commencer, votre consentement est nécessaire pour le traitement d’informations professionnelles ordinaires par les fournisseurs d’IA sélectionnés. N’envoyez aucun mot de passe, clé d’accès, coordonnées bancaires complètes ou identifiant officiel. Répondez «Je consens au traitement» ou «Je ne consens pas». Cela n’autorise ni actions externes, ni exploration personnelle intrusive, ni documents sensibles.",
    "Vor dem Start ist Ihre einmalige Zustimmung zur Verarbeitung gewöhnlicher Geschäftsinformationen durch die gewählten KI-Anbieter nötig. Senden Sie keine Passwörter, Zugangsschlüssel, vollständigen Bankdaten oder amtlichen Kennungen. Antworten Sie „Ich stimme der Verarbeitung zu“ oder „Ich stimme nicht zu“. Externe Aktionen, aufdringliche persönliche Fragen und sensible Dokumente sind damit nicht erlaubt.",
    "Przed rozpoczęciem potrzebna jest jednorazowa zgoda na przetwarzanie zwykłych danych biznesowych przez wybranych dostawców AI. Nie przesyłaj haseł, kluczy, pełnych danych bankowych ani identyfikatorów urzędowych. Napisz „Zgadzam się na przetwarzanie” lub „Nie zgadzam się”. Nie jest to zgoda na działania zewnętrzne, natarczywe pytania osobiste ani poufne dokumenty.",
    "Перед началом нужно ваше разовое согласие на обработку обычных бизнес-данных выбранными ИИ-провайдерами. Не отправляйте пароли, ключи, полные банковские реквизиты или государственные идентификаторы. Напишите «Согласен на обработку» или «Не согласен». Это не разрешение на внешние действия, личные расспросы или чувствительные документы."),
  entry("Вкладення ще не передано ШІ. Його чутливість не визначена. Перевірте, що в ньому немає секретів, і дайте відповідь саме на повідомлення з вкладенням: «Підтверджую документ без секретів». Для відмови: «Відхиляю документ». Підтвердження стосується лише цього вкладення.",
    "The attachment has not been sent to AI. Its sensitivity is unknown. Check that it contains no secrets, then reply directly to that attachment: “I confirm the document contains no secrets”. To reject it: “Reject document”. Confirmation applies only to that attachment.",
    "El archivo aún no se ha enviado a la IA. Comprueba que no contiene secretos y responde directamente al archivo: «Confirmo documento sin secretos». Para rechazarlo: «Rechazar documento». El permiso se aplica solo a ese archivo.",
    "La pièce jointe n’a pas été envoyée à l’IA. Vérifiez l’absence de secrets, puis répondez directement à cette pièce jointe : «Je confirme le document sans secrets». Pour refuser : «Refuser le document». L’autorisation ne concerne que cette pièce jointe.",
    "Der Anhang wurde noch nicht an KI gesendet. Prüfen Sie ihn auf Geheimnisse und antworten Sie direkt darauf: „Dokument ohne Geheimnisse bestätigen“. Zum Ablehnen: „Dokument ablehnen“. Die Freigabe gilt nur für diesen Anhang.",
    "Załącznik nie został przekazany AI. Sprawdź, czy nie zawiera sekretów, i odpowiedz bezpośrednio na niego: „Potwierdzam dokument bez sekretów”. Aby odrzucić: „Odrzuć dokument”. Zgoda dotyczy tylko tego załącznika.",
    "Вложение ещё не передано ИИ. Проверьте отсутствие секретов и ответьте именно на него: «Подтверждаю документ без секретов». Для отказа: «Отклонить документ». Разрешение касается только этого вложения."),
  entry("Роботу призупинено до стандартної десятихвилинної межі; готової відповіді ще немає. Потрібен додатковий час. Напишіть «Продовжити», щоб дозволити наступний обмежений цикл, або «Стоп».",
    "Work paused before the standard ten-minute limit; no final answer is ready. More time is needed. Reply “Continue” to authorise the next bounded cycle, or “Stop”.",
    "El trabajo se pausó antes del límite de diez minutos; aún no hay respuesta final. Responde «Continuar» para autorizar otro ciclo limitado, o «Parar».",
    "Le travail est en pause avant la limite de dix minutes ; aucune réponse finale n’est prête. Répondez «Continuer» pour autoriser un nouveau cycle limité, ou «Arrêter».",
    "Die Arbeit wurde vor dem Zehn-Minuten-Limit pausiert; noch keine endgültige Antwort. Antworten Sie „Weiter“ für einen weiteren begrenzten Zyklus oder „Stopp“.",
    "Praca została wstrzymana przed limitem dziesięciu minut; odpowiedź końcowa nie jest gotowa. Napisz „Kontynuuj”, aby zezwolić na kolejny ograniczony cykl, lub „Stop”.",
    "Работа приостановлена до десятиминутного предела; готового ответа ещё нет. Напишите «Продолжить» для следующего ограниченного цикла или «Стоп»."),
  entry("Сесію зупинено. Нові відповіді цієї задачі не публікуватимуться.", "Session stopped. No new responses for this task will be published.", "Sesión detenida. No se publicarán más respuestas para esta tarea.", "Session arrêtée. Aucune nouvelle réponse ne sera publiée pour cette tâche.", "Sitzung gestoppt. Keine weiteren Antworten zu dieser Aufgabe werden veröffentlicht.", "Sesja zatrzymana. Nowe odpowiedzi do tego zadania nie będą publikowane.", "Сессия остановлена. Новые ответы по этой задаче публиковаться не будут."),
  entry("Попередню роботу зупинено. Надішліть нову задачу окремим повідомленням.", "Previous work stopped. Send the new task as a separate message.", "Trabajo anterior detenido. Envía la nueva tarea en otro mensaje.", "Travail précédent arrêté. Envoyez la nouvelle tâche dans un message séparé.", "Vorherige Arbeit gestoppt. Senden Sie die neue Aufgabe separat.", "Poprzednia praca zatrzymana. Wyślij nowe zadanie w osobnej wiadomości.", "Предыдущая работа остановлена. Отправьте новую задачу отдельным сообщением."),
  entry("Фактична вартість цієї сесії — невідомо. Дані про використання та вартість не отримано; приблизну ціну токенів не підставлено.", "The actual cost of this session is unknown. Usage and cost data are unavailable; no estimated token price has been substituted.", "El coste real de esta sesión es desconocido. No hay datos de uso o coste; no se ha inventado un precio por tokens.", "Le coût réel de cette session est inconnu. Les données d’utilisation et de coût sont indisponibles ; aucun prix estimé n’a été substitué.", "Die tatsächlichen Sitzungskosten sind unbekannt. Nutzungs- und Kostendaten fehlen; kein geschätzter Tokenpreis wurde eingesetzt.", "Rzeczywisty koszt sesji jest nieznany. Brak danych o użyciu i kosztach; nie podstawiono szacunkowej ceny tokenów.", "Фактическая стоимость сессии неизвестна. Данные об использовании и цене недоступны; оценка цены токенов не подставлена."),
  entry("Повідомлення не передано агентам: воно містить можливий секрет або перевищує межу розміру. Надішліть коротший текст без секретів.", "The message was not sent to agents: it may contain a secret or exceed the size limit. Send shorter text without secrets.", "El mensaje no se envió a los agentes: puede contener secretos o ser demasiado largo. Envía un texto más corto sin secretos.", "Le message n’a pas été transmis aux agents : secret possible ou taille excessive. Envoyez un texte plus court sans secrets.", "Nachricht nicht an Agenten gesendet: mögliches Geheimnis oder Größenlimit. Senden Sie einen kürzeren Text ohne Geheimnisse.", "Wiadomość nie trafiła do agentów: możliwy sekret lub przekroczony rozmiar. Wyślij krótszy tekst bez sekretów.", "Сообщение не передано агентам: возможен секрет или превышен размер. Отправьте более короткий текст без секретов."),
  entry("Згоду збережено. Надішліть задачу.", "Consent saved. Send your task.", "Consentimiento guardado. Envía tu tarea.", "Consentement enregistré. Envoyez votre tâche.", "Zustimmung gespeichert. Senden Sie Ihre Aufgabe.", "Zgoda zapisana. Wyślij zadanie.", "Согласие сохранено. Отправьте задачу."),
  entry("Згоду збережено. Запит прийнято.", "Consent saved. Request accepted.", "Consentimiento guardado. Solicitud recibida.", "Consentement enregistré. Demande acceptée.", "Zustimmung gespeichert. Anfrage angenommen.", "Zgoda zapisana. Zgłoszenie przyjęte.", "Согласие сохранено. Запрос принят."),
  entry("Обробку не розпочато. Згоду не надано.", "Processing has not started. Consent was not given.", "El procesamiento no ha comenzado. No se dio consentimiento.", "Le traitement n’a pas commencé. Aucun consentement donné.", "Verarbeitung nicht gestartet. Keine Zustimmung erteilt.", "Przetwarzanie nie rozpoczęło się. Nie udzielono zgody.", "Обработка не началась. Согласие не предоставлено."),
  entry("Дозвіл не застосовано. Спершу надайте загальну згоду, потім дайте відповідь саме на непідтверджене вкладення.", "Permission was not applied. Give general consent first, then reply directly to the unconfirmed attachment.", "El permiso no se aplicó. Da primero el consentimiento general y responde directamente al archivo pendiente.", "Autorisation non appliquée. Donnez d’abord votre consentement général, puis répondez à la pièce jointe non confirmée.", "Freigabe nicht angewendet. Erst allgemeine Zustimmung, dann direkt auf den unbestätigten Anhang antworten.", "Zezwolenie nie zostało zastosowane. Najpierw zgoda ogólna, potem odpowiedź na niepotwierdzony załącznik.", "Разрешение не применено. Сначала дайте общее согласие, затем ответьте на неподтверждённое вложение."),
  entry("Вкладення відхилено. Обробку не розпочато.", "Attachment rejected. Processing has not started.", "Archivo rechazado. El procesamiento no ha comenzado.", "Pièce jointe refusée. Traitement non démarré.", "Anhang abgelehnt. Verarbeitung nicht gestartet.", "Załącznik odrzucony. Przetwarzanie nie rozpoczęło się.", "Вложение отклонено. Обработка не началась."),
  entry("Рішення щодо вкладення збережено. Запит прийнято.", "Attachment decision saved. Request accepted.", "Decisión sobre el archivo guardada. Solicitud recibida.", "Décision sur la pièce jointe enregistrée. Demande acceptée.", "Anhangentscheidung gespeichert. Anfrage angenommen.", "Decyzja dotycząca załącznika zapisana. Zgłoszenie przyjęte.", "Решение по вложению сохранено. Запрос принят."),
  entry("Немає призупиненої роботи, що очікує цього дозволу.", "No paused work is waiting for this permission.", "No hay trabajo pausado esperando este permiso.", "Aucun travail en pause n’attend cette autorisation.", "Keine pausierte Arbeit wartet auf diese Freigabe.", "Żadna wstrzymana praca nie czeka na to zezwolenie.", "Нет приостановленной работы, ожидающей этого разрешения."),
  entry("Дозвіл на наступний обмежений цикл збережено. Налаштування цієї сесії не змінюються.", "Permission for the next bounded cycle saved. Session settings remain unchanged.", "Permiso para el siguiente ciclo limitado guardado. La configuración no cambia.", "Autorisation du prochain cycle limité enregistrée. Paramètres inchangés.", "Freigabe für den nächsten begrenzten Zyklus gespeichert. Einstellungen bleiben unverändert.", "Zgoda na kolejny ograniczony cykl zapisana. Ustawienia sesji pozostają bez zmian.", "Разрешение на следующий ограниченный цикл сохранено. Настройки сессии не меняются."),
  entry("Уточнення не приєднано: відповідь посилається не на поточну задачу. Надішліть уточнення без reply або дайте відповідь на її початкове повідомлення.", "The clarification was not attached: its reply target belongs to another task. Send it without a reply link or reply to this task’s original message.", "La aclaración responde a otra tarea y no se añadió. Envíala sin enlace de respuesta o responde al mensaje original de esta tarea.", "La précision répond à une autre tâche. Envoyez-la sans lien de réponse ou répondez au message initial de cette tâche.", "Die Ergänzung verweist auf eine andere Aufgabe. Ohne Antwortverknüpfung senden oder auf die ursprüngliche Nachricht dieser Aufgabe antworten.", "Uzupełnienie odnosi się do innego zadania. Wyślij je bez powiązania lub odpowiedz na pierwszą wiadomość tego zadania.", "Уточнение относится к другой задаче. Отправьте его без reply или ответьте на исходное сообщение текущей задачи."),
  entry("Уточнення не додано: контекст або вкладення перевищують безпечну межу. Сформулюйте коротше уточнення або почніть «Нова задача».", "Clarification not added: context or attachments exceed safe limits. Shorten it or use “New task”.", "Aclaración no añadida: se superan los límites de contexto o archivos. Acórtala o escribe «Nueva tarea».", "Précision non ajoutée : limites de contexte ou de pièces jointes dépassées. Raccourcissez-la ou écrivez «Nouvelle tâche».", "Ergänzung nicht hinzugefügt: Kontext oder Anhänge überschreiten sichere Grenzen. Kürzen oder „Neue Aufgabe“ senden.", "Uzupełnienie nie dodane: przekroczono limity kontekstu lub załączników. Skróć je lub napisz „Nowe zadanie”.", "Уточнение не добавлено: превышен безопасный предел контекста или вложений. Сократите его или напишите «Новая задача»."),
  entry("Уточнення прийнято до поточної задачі. Попереднє виконання скасовується; чинні налаштування сесії збережено.", "Clarification added to the current task. Previous execution is being cancelled; session settings are preserved.", "Aclaración añadida a la tarea actual. Se cancela la ejecución anterior; se conserva la configuración.", "Précision ajoutée à la tâche actuelle. Exécution précédente annulée ; paramètres conservés.", "Ergänzung zur aktuellen Aufgabe hinzugefügt. Vorherige Ausführung wird abgebrochen; Einstellungen bleiben erhalten.", "Uzupełnienie dodane do bieżącego zadania. Poprzednie wykonanie zostaje anulowane; ustawienia zachowane.", "Уточнение принято к текущей задаче. Предыдущее выполнение отменяется; настройки сохранены."),
  entry("Запит прийнято. Визначаю потрібний формат консультації.", "Request accepted. Determining the appropriate consultation format.", "Solicitud recibida. Determinando el formato de consulta adecuado.", "Demande acceptée. Détermination du format de consultation adapté.", "Anfrage angenommen. Passendes Beratungsformat wird bestimmt.", "Zgłoszenie przyjęte. Dobieram właściwy format konsultacji.", "Запрос принят. Определяю подходящий формат консультации."),
  entry("Продовжую лише фінальний підсумок. Підтверджені позиції, окрему критику й доопрацювання збережено; повторних викликів спеціалістів або Критика не буде.", "Resuming only final synthesis. Confirmed positions, independent critique and revisions are preserved; specialists and Critic will not be called again.", "Se reanuda solo la síntesis final. Se conservan posiciones, crítica y revisiones; no se repetirá a los especialistas ni al Critic.", "Reprise de la synthèse finale uniquement. Positions, critique et révisions conservées ; aucun nouvel appel aux spécialistes ni au Critic.", "Nur die abschließende Synthese wird fortgesetzt. Positionen, Kritik und Überarbeitungen bleiben erhalten; keine erneuten Spezialisten- oder Critic-Aufrufe.", "Wznawiam tylko końcowe podsumowanie. Stanowiska, krytyka i poprawki są zachowane; specjaliści i Critic nie zostaną wywołani ponownie.", "Продолжаю только финальный итог. Позиции, критика и доработки сохранены; повторных вызовов специалистов и Critic не будет."),
  entry("Попередню сесію вже зупинено. Щоб почати нову роботу, надішліть «Нова задача».", "The previous session has already stopped. Send “New task” to start new work.", "La sesión anterior ya se detuvo. Envía «Nueva tarea» para empezar otra.", "La session précédente est arrêtée. Envoyez «Nouvelle tâche» pour recommencer.", "Die vorherige Sitzung ist beendet. Senden Sie „Neue Aufgabe“.", "Poprzednia sesja jest zatrzymana. Napisz „Nowe zadanie”.", "Предыдущая сессия уже остановлена. Напишите «Новая задача»."),
  entry("Виконання перервалося під час перезапуску. Підтверджені репліки збережено. Повторний запуск не виконано автоматично: напишіть «Продовжити» або «Стоп».", "Execution was interrupted by a restart. Confirmed messages are preserved. An uncertain model call was not repeated automatically: reply “Continue” or “Stop”.", "Un reinicio interrumpió la ejecución. Los mensajes confirmados se conservan. No se repitió una llamada incierta al modelo: escribe «Continuar» o «Parar».", "Un redémarrage a interrompu l’exécution. Messages confirmés conservés. Aucun appel incertain au modèle n’a été répété : «Continuer» ou «Arrêter».", "Ausführung durch Neustart unterbrochen. Bestätigte Nachrichten sind erhalten. Ein ungewisser Modellaufruf wurde nicht wiederholt: „Weiter“ oder „Stopp“.", "Restart przerwał wykonanie. Potwierdzone wiadomości zachowane. Nie powtórzono niepewnego wywołania modelu: „Kontynuuj” lub „Stop”.", "Выполнение прервано перезапуском. Подтверждённые сообщения сохранены. Неопределённый вызов модели не повторён: «Продолжить» или «Стоп»."),
  entry("Не вдалося розпочати консультацію: перевірте вибрані моделі й каталог у Налаштуваннях власника. Після виправлення напишіть «Продовжити».", "Consultation could not start: check the selected models and catalog in Owner Settings. After correcting the configuration, reply “Continue”.", "No se pudo iniciar: comprueba modelos y catálogo en los ajustes del propietario. Después escribe «Continuar».", "Démarrage impossible : vérifiez les modèles et le catalogue dans les paramètres du propriétaire. Ensuite, «Continuer».", "Start nicht möglich: Modelle und Katalog in den Eigentümereinstellungen prüfen. Danach „Weiter“ senden.", "Nie można rozpocząć: sprawdź modele i katalog w ustawieniach właściciela. Następnie „Kontynuuj”.", "Не удалось начать: проверьте модели и каталог в настройках владельца. После исправления — «Продолжить»."),
  entry("Очікую завершення поточного запиту до обраного ШІ-провайдера. Нової підтвердженої репліки ще немає.", "Waiting for the selected AI provider to complete the current request. No new confirmed message is available yet.", "Esperando al proveedor de IA. Aún no hay un nuevo mensaje confirmado.", "En attente du fournisseur d’IA. Aucun nouveau message confirmé pour le moment.", "Warte auf den gewählten KI-Anbieter. Noch keine neue bestätigte Nachricht.", "Czekam na wybranego dostawcę AI. Nie ma jeszcze nowej potwierdzonej wiadomości.", "Ожидаю завершения запроса к ИИ-провайдеру. Нового подтверждённого сообщения пока нет."),
  entry("Фінальний підсумок ще не підтверджено. Збережену критику не повторювали. Напишіть «Продовжити» для повтору лише фінального етапу або «Стоп».", "Final synthesis is not yet confirmed. The saved critique was not repeated. Reply “Continue” to retry only the final stage, or “Stop”.", "Síntesis final aún no confirmada. No se repitió la crítica guardada. «Continuar» para reintentar solo el final, o «Parar».", "Synthèse finale non confirmée. Critique sauvegardée non répétée. «Continuer» pour réessayer seulement la fin, ou «Arrêter».", "Abschließende Synthese noch nicht bestätigt. Kritik wurde nicht wiederholt. „Weiter“ nur für den Abschluss oder „Stopp“.", "Końcowe podsumowanie niepotwierdzone. Krytyki nie powtórzono. „Kontynuuj” tylko etap końcowy lub „Stop”.", "Финальный итог не подтверждён. Критика не повторялась. «Продолжить» только финальный этап или «Стоп»."),
  entry("Вкладення не передано агентам: файл прострочений, містить можливий секрет або його не вдалося безпечно прочитати. Для PDF підтримується текстовий шар; скан без тексту, захищений або активний документ не обробляється. Напишіть «Нова задача», потім повторно надішліть задачу з безпечним файлом.", "Attachment not sent to agents: expired, possibly secret, or unsafe to read. PDFs require a text layer; scans without text, protected or active documents are not processed. Send “New task”, then resend with a safe file.", "Archivo no enviado: caducado, posible secreto o lectura insegura. PDF solo con texto; no escaneos sin texto, documentos protegidos o activos. Escribe «Nueva tarea» y envía un archivo seguro.", "Pièce jointe non transmise : expirée, secret possible ou lecture non sûre. PDF avec texte seulement ; pas de scan sans texte ni de document protégé ou actif. «Nouvelle tâche», puis renvoyez un fichier sûr.", "Anhang nicht gesendet: abgelaufen, mögliches Geheimnis oder nicht sicher lesbar. PDF nur mit Textebene; keine textlosen Scans, geschützten oder aktiven Dokumente. „Neue Aufgabe“, dann sichere Datei senden.", "Załącznik nieprzekazany: wygasł, możliwy sekret lub niebezpieczny odczyt. PDF wymaga warstwy tekstowej; bez skanów bez tekstu i dokumentów chronionych lub aktywnych. „Nowe zadanie”, potem bezpieczny plik.", "Вложение не передано: срок истёк, возможен секрет или небезопасно читать. PDF нужен с текстом; сканы без текста, защищённые и активные документы не обрабатываются. «Новая задача», затем безопасный файл."),
  entry("Дані не передано агентам: перевищено межу контексту або знайдено можливий секрет.", "Data not sent to agents: context limit exceeded or possible secret found.", "Datos no enviados: límite de contexto o posible secreto.", "Données non transmises : limite de contexte ou secret possible.", "Daten nicht gesendet: Kontextlimit oder mögliches Geheimnis.", "Dane nieprzekazane: limit kontekstu lub możliwy sekret.", "Данные не переданы: предел контекста или возможный секрет."),
  entry("Консультацію не завершено: обраний ШІ-провайдер або його відповідь зараз недоступні. Перевірте runtime і напишіть «Продовжити» для явної повторної спроби.", "Consultation incomplete: the selected AI provider or its response is unavailable. Check provider readiness and reply “Continue” for an explicit retry.", "Consulta incompleta: proveedor o respuesta no disponible. Comprueba su disponibilidad y escribe «Continuar» para reintentar.", "Consultation inachevée : fournisseur ou réponse indisponible. Vérifiez sa disponibilité et écrivez «Continuer» pour réessayer.", "Beratung unvollständig: Anbieter oder Antwort nicht verfügbar. Verfügbarkeit prüfen und „Weiter“ für einen ausdrücklichen Wiederholungsversuch.", "Konsultacja nieukończona: dostawca lub odpowiedź niedostępne. Sprawdź gotowość i napisz „Kontynuuj”, aby ponowić.", "Консультация не завершена: провайдер или ответ недоступны. Проверьте готовность и напишите «Продолжить» для явного повтора."),
  entry("Відповідь заблоковано перевіркою конфіденційності.", "The response was blocked by the privacy check.", "Respuesta bloqueada por la comprobación de privacidad.", "Réponse bloquée par le contrôle de confidentialité.", "Antwort durch Datenschutzprüfung blockiert.", "Odpowiedź zablokowana przez kontrolę poufności.", "Ответ заблокирован проверкой конфиденциальности."),
  entry("Отриманий матеріал перевищує межу контексту або не пройшов перевірку конфіденційності.", "The material exceeds the context limit or failed the privacy check.", "El material supera el contexto o no pasó la comprobación de privacidad.", "Le contenu dépasse le contexte ou a échoué au contrôle de confidentialité.", "Material überschreitet Kontextlimit oder besteht Datenschutzprüfung nicht.", "Materiał przekracza kontekst lub nie przeszedł kontroli poufności.", "Материал превышает контекст или не прошёл проверку конфиденциальности."),
  entry("Консультацію не завершено. Критичний або фінальний етап не підтверджено; готову рекомендацію не оголошено. Напишіть «Продовжити» для явної повторної спроби або «Стоп».", "Consultation incomplete. The review or final stage is unconfirmed; no completed recommendation is claimed. Reply “Continue” for an explicit retry or “Stop”.", "Consulta incompleta. Revisión o final sin confirmar; no se afirma una recomendación terminada. «Continuar» para reintentar o «Parar».", "Consultation inachevée. Révision ou fin non confirmée ; aucune recommandation achevée annoncée. «Continuer» ou «Arrêter».", "Beratung unvollständig. Prüfung oder Abschluss nicht bestätigt; keine fertige Empfehlung behauptet. „Weiter“ oder „Stopp“.", "Konsultacja nieukończona. Przegląd lub finał niepotwierdzony; nie ogłoszono gotowej rekomendacji. „Kontynuuj” lub „Stop”.", "Консультация не завершена. Проверка или финал не подтверждены; готовая рекомендация не объявлена. «Продолжить» или «Стоп»."),
  entry("Консультацію перервано без готової відповіді. Повторного запуску не буде без команди «Продовжити».", "Consultation interrupted without a final answer. It will not restart without “Continue”.", "Consulta interrumpida sin respuesta final. No se reiniciará sin «Continuar».", "Consultation interrompue sans réponse finale. Pas de reprise sans «Continuer».", "Beratung ohne endgültige Antwort unterbrochen. Kein Neustart ohne „Weiter“.", "Konsultacja przerwana bez końcowej odpowiedzi. Nie wznowi się bez „Kontynuuj”.", "Консультация прервана без готового ответа. Повтор только по команде «Продолжить»."),
  entry("Роботу перервано через зміну доступності або керування сесією. Підтверджені репліки збережено; автоматичного повтору немає. Напишіть «Продовжити» або «Стоп».", "Work interrupted by an availability or session-control change. Confirmed messages are preserved; no automatic model retry. Reply “Continue” or “Stop”.", "Trabajo interrumpido por disponibilidad o control de sesión. Mensajes confirmados conservados; sin repetición automática del modelo. «Continuar» o «Parar».", "Travail interrompu par disponibilité ou contrôle de session. Messages confirmés conservés ; pas de répétition automatique du modèle. «Continuer» ou «Arrêter».", "Arbeit wegen Verfügbarkeits- oder Sitzungsänderung unterbrochen. Bestätigte Nachrichten erhalten; keine automatische Modellwiederholung. „Weiter“ oder „Stopp“.", "Praca przerwana przez dostępność lub sterowanie sesją. Potwierdzone wiadomości zachowane; brak automatycznego powtórzenia modelu. „Kontynuuj” lub „Stop”.", "Работа прервана из-за доступности или управления сессией. Сообщения сохранены; автоматического повтора модели нет. «Продолжить» или «Стоп».")
]);

/** Universal exact control commands are structural placeholders in the
 * translation source. A model cannot invent a new permission-granting phrase. */
const CONTROL_TOKENS = Object.freeze({
  "[[CONSENT]]": "I consent to processing", "[[DECLINE_CONSENT]]": "I do not consent",
  "[[CONFIRM_DOCUMENT]]": "I confirm the document contains no secrets", "[[REJECT_DOCUMENT]]": "Reject document",
  "[[CONTINUE]]": "Continue", "[[STOP]]": "Stop", "[[NEW_TASK]]": "New task"
});
const templateFor = (message: string): string => Object.entries(CONTROL_TOKENS)
  .reduce((body, [token, command]) => body.replaceAll(`“${command}”`, token), message);
export const SERVICE_TRANSLATION_SOURCE: Readonly<Record<string, string>> = Object.freeze(Object.fromEntries(
  SERVICE_MESSAGES.map((message, index) => [`notice_${String(index + 1).padStart(3, "0")}`, templateFor(message.en)])
));
export type ServiceTranslationCatalog = Readonly<{
  language: string;
  sourceHash: string;
  messages: Readonly<Record<string, string>>;
}>;
export async function serviceTranslationSourceHash(): Promise<string> {
  const bytes = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(SERVICE_TRANSLATION_SOURCE)));
  return [...new Uint8Array(bytes)].map(value => value.toString(16).padStart(2, "0")).join("");
}
export async function validateServiceTranslationCatalog(value: unknown, expectedLanguage: string): Promise<ServiceTranslationCatalog | undefined> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return undefined;
  const record = value as Record<string, unknown>;
  const canonical = canonicalSessionLanguage(expectedLanguage);
  if (canonical === undefined || Object.keys(record).sort().join(",") !== "language,messages,sourceHash" ||
    record.language !== canonical || record.sourceHash !== await serviceTranslationSourceHash() || record.messages === null ||
    typeof record.messages !== "object" || Array.isArray(record.messages)) return undefined;
  const messages = record.messages as Record<string, unknown>;
  if (Object.keys(messages).sort().join(",") !== Object.keys(SERVICE_TRANSLATION_SOURCE).sort().join(",") ||
    new TextEncoder().encode(JSON.stringify(messages)).byteLength > 64_000) return undefined;
  if (canonical.split("-")[0] !== "en" && Object.entries(SERVICE_TRANSLATION_SOURCE).every(([id, source]) => messages[id] === source)) return undefined;
  const tokens = (body: string): string => (body.match(/\[\[[A-Z_]+\]\]/gu) ?? []).sort().join(",");
  for (const [id, source] of Object.entries(SERVICE_TRANSLATION_SOURCE)) {
    const text = messages[id];
    if (typeof text !== "string" || text.trim().length === 0 || new TextEncoder().encode(text).byteLength > 4_000 ||
      /[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f<>]/u.test(text) || /https?:\/\/|www\./iu.test(text) || tokens(text) !== tokens(source)) return undefined;
  }
  return Object.freeze({ language: canonical, sourceHash: record.sourceHash as string, messages: Object.freeze({ ...messages } as Record<string, string>) });
}
function expandControlTokens(body: string): string {
  return Object.entries(CONTROL_TOKENS).reduce((text, [token, command]) => text.replaceAll(token, `“${command}”`), body);
}

/** Translates only application-authored notices. Never transform agent bodies. */
export function serviceMessage(ukSource: string, language: string | null | undefined, translated?: ServiceTranslationCatalog): string {
  const locale = supportedServiceLanguage(language);
  const message = SERVICE_MESSAGES.find(value => value.uk === ukSource);
  if (message === undefined) throw new Error("unregistered_service_message");
  const id = `notice_${String(SERVICE_MESSAGES.indexOf(message) + 1).padStart(3, "0")}`;
  if (translated !== undefined && translated.language === canonicalSessionLanguage(language) && translated.messages[id] !== undefined)
    return expandControlTokens(translated.messages[id]!);
  if (locale === undefined) {
    const canonical = canonicalSessionLanguage(language);
    return canonical === undefined ? LANGUAGE_QUESTION : `[Service notices are not yet translated into ${canonical}; English follows. AI consultation language remains ${canonical}.]\n\n${message.en}`;
  }
  return message[locale];
}

export function parseLanguageAnswer(body: string): string | undefined {
  const name = body.trim().toLocaleLowerCase("en");
  const names: Readonly<Record<string, string>> = { english: "en", en: "en", українська: "uk", українською: "uk", ukrainian: "uk", uk: "uk", español: "es", spanish: "es", es: "es", français: "fr", french: "fr", fr: "fr", deutsch: "de", german: "de", de: "de", polski: "pl", polish: "pl", pl: "pl", русский: "ru", russian: "ru", ru: "ru" };
  return names[name] ?? canonicalSessionLanguage(name);
}
